### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by niccoX** [unnikked/cloudflare-dns-manager#1]
I'm trying to execute the script on a Mac. I installed jq through brew. I end up with a line error when executing the script, both with the correct tokenid etc.

| => ./dyndns.sh your@email.com tokenid CREATE niko.com A ftp.niko.com 0
Using your public ip: xx.xx.xxx.xxx
./dyndns.sh: line 49: -1: substring expression < 0

**Comment by unnikked** [comment]
Which version of Bash are you using ? Probably it does not support the construct

``` bash
${RES:1:-1}
```

for substrings. Unfortunately I'm not familiar with the Mac environment.

**Comment by niccoX** [comment]
Seems related to MAC.

I got it working on a CentOS box.

Bash version: 3.2.53(1)-release

EDIT:

Sorted it out by executing the scipt with:

bash ./dyndn.sh
